# Generated by Django 6.0.3 on 2026-04-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donationimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('received', 'Recibida'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('distributed', 'Distribuida'), ('cancelled', 'Cancelada')], default='pending', max_length=20),
        ),
    ]
