# Generated by Django 6.0.3 on 2026-04-19 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_remove_campaign_goal_activitylocation_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activityvolunteer',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityvolunteer',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityvolunteer',
            name='hours_contributed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='activityvolunteer',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='collected_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='notes_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='campaign',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_activities',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_volunteers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaignactivity',
            name='assigned_volunteers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaignactivity',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaignactivity',
            name='max_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignactivity',
            name='notes_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignactivity',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='campaignactivity',
            name='requires_transport',
            field=models.BooleanField(default=False),
        ),
    ]
