# Generated by Django 6.0.3 on 2026-04-22 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_activityvolunteer_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylocation',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='campaigns.campaignactivity'),
        ),
    ]
