# Generated by Django 6.0.3 on 2026-04-22 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_alter_activitylocation_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylocation',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='campaigns.campaignactivity'),
        ),
    ]
